version: '2'
services:
  ui:
    build: ./web
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - '3002:3002'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
